"""Orders, fills and positions.

Orders carry a ``client_order_id`` unique per mode and run: that uniqueness
constraint is the duplicate-order protection required by the safety rules. A
retry after a timeout reuses the same id, so the database refuses to create a
second order.

``mode`` (PAPER / LIVE / BACKTEST) is on every row here. Paper, live and
replayed results must never be summed together, and the column makes that
mistake impossible to make silently. ``backtest_run_id`` does the same between
two backtests, which share a mode - see ``db.models.backtest``.

Two of the old ``mode``-keyed unique constraints have nullable key columns
(``execution_intent_id``/``signal_leg``, ``attempt_id``), and every order
written before Phase 8's remediation has NULL intent keys. Adding a nullable
run column to them with ``NULLS NOT DISTINCT`` would suddenly make those
legacy rows collide, so each became two partial unique indexes instead - one
for rows outside any run, one per run - which keeps their exact semantics.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    false,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from trading_bot.db.base import Base, RecordMixin
from trading_bot.db.models.backtest import (
    BACKTEST_MODE_HAS_RUN,
    RUN_KEY_MATCHES_RUN,
    backtest_run_fk,
    run_key_column,
    run_key_target,
    run_scoped_fk,
)
from trading_bot.db.models.enum_types import (
    EXECUTION_MODE,
    ORDER_STATUS,
    ORDER_TYPE,
    POSITION_STATUS,
    SIDE,
    TIME_IN_FORCE,
)
from trading_bot.db.models.enums import (
    ExecutionMode,
    OrderStatus,
    OrderType,
    PositionStatus,
    Side,
    TimeInForce,
)
from trading_bot.db.models.market import Market
from trading_bot.db.models.research import STRATEGY_NAME_LENGTH, Signal
from trading_bot.db.models.types import BPS, MONEY, PRICE, QUANTITY


class Order(Base, RecordMixin):
    """An order the system intended to place, paper or live."""

    __tablename__ = "orders"

    # Provenance: which signal asked for this, and which risk decision allowed it.
    # ``signal_id`` is NULL while an episode is still open: signals are
    # written when the episode closes, which is after the order was placed.
    # ``opportunity_uid`` carries the link in the meantime - the episode's id
    # is fixed the moment it opens, so an order can name the opportunity it
    # came from before that opportunity has a row.
    signal_id: Mapped[int | None] = mapped_column(BigInteger)
    opportunity_uid: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    # A probe, not a trade the strategy asked for. Measured live, no
    # opportunity on this account has ever passed validation, so the only way
    # to find out what a round trip costs is to simulate one deliberately -
    # and then keep it out of every question about what the strategy earned.
    is_shadow: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=false()
    )
    execution_intent_id: Mapped[str | None] = mapped_column(String(80))
    attempt_id: Mapped[str | None] = mapped_column(String(64))
    signal_leg: Mapped[int | None] = mapped_column(Integer)
    intent: Mapped[str | None] = mapped_column(String(16))
    strategy: Mapped[str | None] = mapped_column(String(STRATEGY_NAME_LENGTH))
    risk_event_id: Mapped[int | None] = mapped_column(BigInteger)
    market_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("markets.id", ondelete="RESTRICT"), nullable=False
    )
    mode: Mapped[ExecutionMode] = mapped_column(EXECUTION_MODE, nullable=False)
    backtest_run_id: Mapped[int | None] = backtest_run_fk()
    run_key: Mapped[int] = run_key_column()

    # Idempotency key generated by us before submission.
    client_order_id: Mapped[str] = mapped_column(String(64), nullable=False)
    # Venue id, absent for paper orders and for live orders that never reached
    # the exchange.
    exchange_order_id: Mapped[str | None] = mapped_column(String(64))

    side: Mapped[Side] = mapped_column(SIDE, nullable=False)
    order_type: Mapped[OrderType] = mapped_column(ORDER_TYPE, nullable=False)
    time_in_force: Mapped[TimeInForce | None] = mapped_column(TIME_IN_FORCE)
    quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False)
    # NULL for market orders.
    price: Mapped[Decimal | None] = mapped_column(PRICE)
    expected_price: Mapped[Decimal | None] = mapped_column(PRICE)

    filled_quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False, default=0)
    average_fill_price: Mapped[Decimal | None] = mapped_column(PRICE)

    status: Mapped[OrderStatus] = mapped_column(
        ORDER_STATUS, nullable=False, default=OrderStatus.PENDING
    )
    # Every terminal failure state must say why.
    rejection_reason: Mapped[str | None] = mapped_column(Text)

    submitted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Submission to acknowledgement; the number the risk engine limits.
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    terminal_latency_ms: Mapped[int | None] = mapped_column(Integer)
    book_sequence: Mapped[int | None] = mapped_column(BigInteger)
    book_local_timestamp: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    evidence: Mapped[dict[str, object] | None] = mapped_column(JSONB)

    signal: Mapped[Signal | None] = relationship(
        primaryjoin="Order.signal_id == Signal.id", foreign_keys=[signal_id], lazy="raise"
    )
    market: Mapped[Market] = relationship(lazy="raise")
    fills: Mapped[list[Fill]] = relationship(
        back_populates="order",
        primaryjoin="Order.id == Fill.order_id",
        foreign_keys="[Fill.order_id]",
        lazy="raise",
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        # Links within one run only (``backtest.run_key_column``).
        CheckConstraint(RUN_KEY_MATCHES_RUN, name="run_key_matches_run"),
        run_key_target(),
        run_scoped_fk("signal_id", "signals", ondelete="SET NULL"),
        run_scoped_fk("risk_event_id", "risk_events", ondelete="SET NULL"),
        # Duplicate-order protection: a retry cannot create a second order.
        # NULLS NOT DISTINCT so rows outside any run still collide with each
        # other; every other key column is NOT NULL.
        UniqueConstraint(
            "mode",
            "backtest_run_id",
            "client_order_id",
            name="mode_run_client_order_id",
            postgresql_nulls_not_distinct=True,
        ),
        Index(
            "ux_orders_live_intent_leg",
            "mode",
            "execution_intent_id",
            "signal_leg",
            unique=True,
            postgresql_where=text("backtest_run_id IS NULL"),
        ),
        Index(
            "ux_orders_run_intent_leg",
            "backtest_run_id",
            "execution_intent_id",
            "signal_leg",
            unique=True,
            postgresql_where=text("backtest_run_id IS NOT NULL"),
        ),
        Index("ix_orders_run_created", "backtest_run_id", "created_at"),
        CheckConstraint(BACKTEST_MODE_HAS_RUN, name="backtest_mode_has_run"),
        Index("ix_orders_status_created", "status", "created_at"),
        Index("ix_orders_market_created", "market_id", "created_at"),
        Index("ix_orders_mode_created", "mode", "created_at"),
        Index("ix_orders_exchange_order_id", "exchange_order_id"),
        # "What did we actually do about this opportunity?"
        Index("ix_orders_opportunity_uid", "opportunity_uid"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
        CheckConstraint("price IS NULL OR price > 0", name="price_positive"),
        CheckConstraint("filled_quantity >= 0", name="filled_non_negative"),
        # A fill larger than the order means a reconciliation bug.
        CheckConstraint("filled_quantity <= quantity", name="filled_within_quantity"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<Order {self.mode} {self.side} {self.quantity} {self.status}>"


class Fill(Base, RecordMixin):
    """An execution against an order. Partial fills produce several rows."""

    __tablename__ = "fills"

    order_id: Mapped[int] = mapped_column(BigInteger, nullable=False)
    position_id: Mapped[int | None] = mapped_column(BigInteger)
    mode: Mapped[ExecutionMode] = mapped_column(EXECUTION_MODE, nullable=False)
    backtest_run_id: Mapped[int | None] = backtest_run_fk()
    run_key: Mapped[int] = run_key_column()

    # Venue fill id where available; NULL for simulated fills.
    exchange_fill_id: Mapped[str | None] = mapped_column(String(64))
    price: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False)

    fee_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    fee_asset: Mapped[str | None] = mapped_column(String(16))
    fee_rate_bps: Mapped[Decimal | None] = mapped_column(BPS)
    # Realised slippage against the price the strategy expected - the number
    # that decides whether the paper simulation was honest.
    slippage_bps: Mapped[Decimal | None] = mapped_column(BPS)
    is_maker: Mapped[bool | None] = mapped_column(Boolean)

    filled_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    fill_index: Mapped[int | None] = mapped_column(Integer)
    book_sequence: Mapped[int | None] = mapped_column(BigInteger)
    book_local_timestamp: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    levels: Mapped[list[dict[str, str]] | None] = mapped_column(JSONB)

    order: Mapped[Order] = relationship(
        back_populates="fills",
        primaryjoin="Order.id == Fill.order_id",
        foreign_keys=[order_id],
        lazy="raise",
    )
    position: Mapped[Position | None] = relationship(
        back_populates="fills",
        primaryjoin="Position.id == Fill.position_id",
        foreign_keys=[position_id],
        lazy="raise",
    )

    __table_args__ = (
        # Links within one run only (``backtest.run_key_column``).
        CheckConstraint(RUN_KEY_MATCHES_RUN, name="run_key_matches_run"),
        run_scoped_fk("order_id", "orders", ondelete="CASCADE"),
        run_scoped_fk("position_id", "positions", ondelete="SET NULL"),
        # Duplicate-message protection for live fill streams.
        UniqueConstraint("order_id", "exchange_fill_id", name="order_exchange_fill_id"),
        UniqueConstraint("order_id", "fill_index", name="order_fill_index"),
        Index("ix_fills_order", "order_id"),
        Index("ix_fills_filled_at", "filled_at"),
        Index("ix_fills_position", "position_id"),
        Index("ix_fills_run_filled_at", "backtest_run_id", "filled_at"),
        CheckConstraint(BACKTEST_MODE_HAS_RUN, name="backtest_mode_has_run"),
        CheckConstraint("price > 0", name="price_positive"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
    )


class Position(Base, RecordMixin):
    """An open or closed exposure in one market.

    Realized P&L is stored rather than derived on read: it depends on the fee
    and slippage assumptions in force at the time, and recomputing it later
    against changed assumptions would rewrite history.

    Phase 10 adds the exit half. Every exit column is **recomputed from the
    position's own CLOSE fills** rather than incremented, which is what makes
    a retried close, a crash between submission and recording, and a restart
    all converge on the same row instead of double-counting one. See
    ``trading_bot.portfolio.accounting`` for the exact formulas and
    ``docs/data-model.md`` for the sign conventions.
    """

    __tablename__ = "positions"

    market_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("markets.id", ondelete="RESTRICT"), nullable=False
    )
    # Which opportunity this exposure came from; NULL for manual interventions.
    opportunity_id: Mapped[int | None] = mapped_column(BigInteger)
    opportunity_uid: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    attempt_id: Mapped[str | None] = mapped_column(String(64))
    # Hypothetical probes are persisted for execution research but must never
    # be restored into, or reported as, the strategy's paper portfolio.
    is_shadow: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=false()
    )
    mode: Mapped[ExecutionMode] = mapped_column(EXECUTION_MODE, nullable=False)
    backtest_run_id: Mapped[int | None] = backtest_run_fk()
    run_key: Mapped[int] = run_key_column()
    strategy: Mapped[str] = mapped_column(String(STRATEGY_NAME_LENGTH), nullable=False)
    side: Mapped[Side] = mapped_column(SIDE, nullable=False)
    status: Mapped[PositionStatus] = mapped_column(
        POSITION_STATUS, nullable=False, default=PositionStatus.OPEN
    )

    # Opened size (weighted over the entry fills) and how much of it CLOSE
    # fills have given back. ``quantity - closed_quantity`` is the exposure
    # that still exists, and the only quantity an exit may ever ask for.
    quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False)
    closed_quantity: Mapped[Decimal] = mapped_column(
        QUANTITY, nullable=False, default=0, server_default=text("0")
    )
    entry_price: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    # Weighted average of the CLOSE fills; NULL until one exists.
    exit_price: Mapped[Decimal | None] = mapped_column(PRICE)
    entry_notional_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False)
    exit_notional_usd: Mapped[Decimal | None] = mapped_column(MONEY)

    # Net of fees, on the closed portion only. An open or partially closed
    # position never counts its unclosed remainder here.
    realized_pnl_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    # Signed price P&L on the closed portion, BEFORE fees - kept separately so
    # "what did the basis do" and "what did the venue charge" stay legible.
    price_pnl_usd: Mapped[Decimal | None] = mapped_column(MONEY)
    unrealized_pnl_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    # Total fees charged on this position, entry plus exit; ``exit_fees_usd``
    # is the exit share of it, so entry fees are ``fees_usd - exit_fees_usd``.
    fees_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    exit_fees_usd: Mapped[Decimal] = mapped_column(
        MONEY, nullable=False, default=0, server_default=text("0")
    )
    # Attribution only. Slippage is already inside the fill prices above; it
    # is recorded so the cost model can be checked and is NEVER subtracted
    # from realized P&L a second time.
    slippage_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    exit_slippage_usd: Mapped[Decimal] = mapped_column(
        MONEY, nullable=False, default=0, server_default=text("0")
    )
    # Cash flows nothing in this system can measure yet. NULL means
    # "not measured", never zero: a position that paid funding and one that
    # crossed no settlement must not read the same. ``unmeasured_pnl`` names
    # them, so a realized total is never silently presented as complete.
    funding_pnl_usd: Mapped[Decimal | None] = mapped_column(MONEY)
    borrow_cost_usd: Mapped[Decimal | None] = mapped_column(MONEY)
    unmeasured_pnl: Mapped[list[str] | None] = mapped_column(JSONB)

    # Mark used for the newest unrealized figure, and when it was taken. A
    # stale or missing mark leaves both NULL rather than reusing an old one.
    mark_price: Mapped[Decimal | None] = mapped_column(PRICE)
    marked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # The exit in flight, or the one that closed this position. The claim
    # columns are how two workers cannot close the same position: claiming
    # writes ``status = CLOSING`` under a row lock in one transaction.
    close_intent_id: Mapped[str | None] = mapped_column(String(80))
    close_claim_id: Mapped[str | None] = mapped_column(String(64))
    close_claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Incremented per claim, so a retried exit after a failed one gets fresh
    # deterministic order ids instead of colliding with the previous attempt.
    close_attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )
    exit_reason: Mapped[str | None] = mapped_column(String(32))

    opened_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    market: Mapped[Market] = relationship(lazy="raise")
    fills: Mapped[list[Fill]] = relationship(
        back_populates="position",
        primaryjoin="Position.id == Fill.position_id",
        foreign_keys="[Fill.position_id]",
        lazy="raise",
    )

    __table_args__ = (
        # Links within one run only (``backtest.run_key_column``).
        CheckConstraint(RUN_KEY_MATCHES_RUN, name="run_key_matches_run"),
        run_key_target(),
        run_scoped_fk("opportunity_id", "opportunities", ondelete="SET NULL"),
        Index("ix_positions_status_opened", "status", "opened_at"),
        Index("ix_positions_market_opened", "market_id", "opened_at"),
        Index("ix_positions_mode_strategy", "mode", "strategy"),
        # "Which trades completed today?" - the daily-loss and
        # consecutive-loss gates' only query, and the P&L windows'.
        Index("ix_positions_mode_closed_at", "mode", "closed_at"),
        Index("ix_positions_run_closed_at", "backtest_run_id", "closed_at"),
        # One position per leg of an attempt, per scope. Partial indexes, not
        # NULLS NOT DISTINCT: ``attempt_id`` is nullable and a NULL attempt
        # must stay distinct, exactly as it was.
        Index(
            "ux_positions_live_attempt_market",
            "mode",
            "attempt_id",
            "market_id",
            unique=True,
            postgresql_where=text("backtest_run_id IS NULL"),
        ),
        Index(
            "ux_positions_run_attempt_market",
            "backtest_run_id",
            "attempt_id",
            "market_id",
            unique=True,
            postgresql_where=text("backtest_run_id IS NOT NULL"),
        ),
        CheckConstraint(BACKTEST_MODE_HAS_RUN, name="backtest_mode_has_run"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
        CheckConstraint("entry_price > 0", name="entry_price_positive"),
        CheckConstraint("exit_price IS NULL OR exit_price > 0", name="exit_price_positive"),
        # A closed position must record when and at what price.
        CheckConstraint(
            "status <> 'CLOSED' OR (closed_at IS NOT NULL AND exit_price IS NOT NULL)",
            name="closed_position_complete",
        ),
        # Reduce-only, enforced by the database rather than only by the code
        # that is supposed to respect it: no sequence of closes can give back
        # more than was opened, or reverse the position into the other side.
        CheckConstraint("closed_quantity >= 0", name="closed_quantity_non_negative"),
        CheckConstraint("closed_quantity <= quantity", name="closed_within_quantity"),
        CheckConstraint("close_attempts >= 0", name="close_attempts_non_negative"),
        CheckConstraint(
            "exit_notional_usd IS NULL OR exit_notional_usd >= 0",
            name="exit_notional_non_negative",
        ),
        # A fully closed position has given every unit back; anything less is
        # still carrying exposure and must not read as CLOSED.
        CheckConstraint(
            "status <> 'CLOSED' OR closed_quantity = quantity",
            name="closed_position_flat",
        ),
    )
