"""Orders, fills and positions.

Orders carry a ``client_order_id`` unique per mode: that uniqueness constraint
is the duplicate-order protection required by the safety rules. A retry after a
timeout reuses the same id, so the database refuses to create a second order.

``mode`` (PAPER / LIVE) is on every row here. Paper and live results must never
be summed together, and the column makes that mistake impossible to make
silently.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    false,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from trading_bot.db.base import Base, RecordMixin
from trading_bot.db.models.enum_types import (
    EXECUTION_MODE,
    ORDER_STATUS,
    ORDER_TYPE,
    POSITION_STATUS,
    SIDE,
    TIME_IN_FORCE,
)
from trading_bot.db.models.enums import (
    ExecutionMode,
    OrderStatus,
    OrderType,
    PositionStatus,
    Side,
    TimeInForce,
)
from trading_bot.db.models.market import Market
from trading_bot.db.models.research import STRATEGY_NAME_LENGTH, Signal
from trading_bot.db.models.types import BPS, MONEY, PRICE, QUANTITY


class Order(Base, RecordMixin):
    """An order the system intended to place, paper or live."""

    __tablename__ = "orders"

    # Provenance: which signal asked for this, and which risk decision allowed it.
    # ``signal_id`` is NULL while an episode is still open: signals are
    # written when the episode closes, which is after the order was placed.
    # ``opportunity_uid`` carries the link in the meantime - the episode's id
    # is fixed the moment it opens, so an order can name the opportunity it
    # came from before that opportunity has a row.
    signal_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("signals.id", ondelete="SET NULL")
    )
    opportunity_uid: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    # A probe, not a trade the strategy asked for. Measured live, no
    # opportunity on this account has ever passed validation, so the only way
    # to find out what a round trip costs is to simulate one deliberately -
    # and then keep it out of every question about what the strategy earned.
    is_shadow: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=false()
    )
    execution_intent_id: Mapped[str | None] = mapped_column(String(80))
    attempt_id: Mapped[str | None] = mapped_column(String(64))
    signal_leg: Mapped[int | None] = mapped_column(Integer)
    intent: Mapped[str | None] = mapped_column(String(16))
    strategy: Mapped[str | None] = mapped_column(String(STRATEGY_NAME_LENGTH))
    risk_event_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("risk_events.id", ondelete="SET NULL")
    )
    market_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("markets.id", ondelete="RESTRICT"), nullable=False
    )
    mode: Mapped[ExecutionMode] = mapped_column(EXECUTION_MODE, nullable=False)

    # Idempotency key generated by us before submission.
    client_order_id: Mapped[str] = mapped_column(String(64), nullable=False)
    # Venue id, absent for paper orders and for live orders that never reached
    # the exchange.
    exchange_order_id: Mapped[str | None] = mapped_column(String(64))

    side: Mapped[Side] = mapped_column(SIDE, nullable=False)
    order_type: Mapped[OrderType] = mapped_column(ORDER_TYPE, nullable=False)
    time_in_force: Mapped[TimeInForce | None] = mapped_column(TIME_IN_FORCE)
    quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False)
    # NULL for market orders.
    price: Mapped[Decimal | None] = mapped_column(PRICE)
    expected_price: Mapped[Decimal | None] = mapped_column(PRICE)

    filled_quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False, default=0)
    average_fill_price: Mapped[Decimal | None] = mapped_column(PRICE)

    status: Mapped[OrderStatus] = mapped_column(
        ORDER_STATUS, nullable=False, default=OrderStatus.PENDING
    )
    # Every terminal failure state must say why.
    rejection_reason: Mapped[str | None] = mapped_column(Text)

    submitted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Submission to acknowledgement; the number the risk engine limits.
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    terminal_latency_ms: Mapped[int | None] = mapped_column(Integer)
    book_sequence: Mapped[int | None] = mapped_column(BigInteger)
    book_local_timestamp: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    evidence: Mapped[dict[str, object] | None] = mapped_column(JSONB)

    signal: Mapped[Signal | None] = relationship(lazy="raise")
    market: Mapped[Market] = relationship(lazy="raise")
    fills: Mapped[list[Fill]] = relationship(
        back_populates="order", lazy="raise", cascade="all, delete-orphan"
    )

    __table_args__ = (
        # Duplicate-order protection: a retry cannot create a second order.
        UniqueConstraint("mode", "client_order_id", name="mode_client_order_id"),
        UniqueConstraint(
            "mode",
            "execution_intent_id",
            "signal_leg",
            name="mode_execution_intent_leg",
        ),
        Index("ix_orders_status_created", "status", "created_at"),
        Index("ix_orders_market_created", "market_id", "created_at"),
        Index("ix_orders_mode_created", "mode", "created_at"),
        Index("ix_orders_exchange_order_id", "exchange_order_id"),
        # "What did we actually do about this opportunity?"
        Index("ix_orders_opportunity_uid", "opportunity_uid"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
        CheckConstraint("price IS NULL OR price > 0", name="price_positive"),
        CheckConstraint("filled_quantity >= 0", name="filled_non_negative"),
        # A fill larger than the order means a reconciliation bug.
        CheckConstraint("filled_quantity <= quantity", name="filled_within_quantity"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<Order {self.mode} {self.side} {self.quantity} {self.status}>"


class Fill(Base, RecordMixin):
    """An execution against an order. Partial fills produce several rows."""

    __tablename__ = "fills"

    order_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False
    )
    position_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("positions.id", ondelete="SET NULL")
    )
    mode: Mapped[ExecutionMode] = mapped_column(EXECUTION_MODE, nullable=False)

    # Venue fill id where available; NULL for simulated fills.
    exchange_fill_id: Mapped[str | None] = mapped_column(String(64))
    price: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False)

    fee_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    fee_asset: Mapped[str | None] = mapped_column(String(16))
    fee_rate_bps: Mapped[Decimal | None] = mapped_column(BPS)
    # Realised slippage against the price the strategy expected - the number
    # that decides whether the paper simulation was honest.
    slippage_bps: Mapped[Decimal | None] = mapped_column(BPS)
    is_maker: Mapped[bool | None] = mapped_column(Boolean)

    filled_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    fill_index: Mapped[int | None] = mapped_column(Integer)
    book_sequence: Mapped[int | None] = mapped_column(BigInteger)
    book_local_timestamp: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    levels: Mapped[list[dict[str, str]] | None] = mapped_column(JSONB)

    order: Mapped[Order] = relationship(back_populates="fills", lazy="raise")
    position: Mapped[Position | None] = relationship(back_populates="fills", lazy="raise")

    __table_args__ = (
        # Duplicate-message protection for live fill streams.
        UniqueConstraint("order_id", "exchange_fill_id", name="order_exchange_fill_id"),
        UniqueConstraint("order_id", "fill_index", name="order_fill_index"),
        Index("ix_fills_order", "order_id"),
        Index("ix_fills_filled_at", "filled_at"),
        Index("ix_fills_position", "position_id"),
        CheckConstraint("price > 0", name="price_positive"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
    )


class Position(Base, RecordMixin):
    """An open or closed exposure in one market.

    Realized P&L is stored rather than derived on read: it depends on the fee
    and slippage assumptions in force at the time, and recomputing it later
    against changed assumptions would rewrite history.
    """

    __tablename__ = "positions"

    market_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("markets.id", ondelete="RESTRICT"), nullable=False
    )
    # Which opportunity this exposure came from; NULL for manual interventions.
    opportunity_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("opportunities.id", ondelete="SET NULL")
    )
    opportunity_uid: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))
    attempt_id: Mapped[str | None] = mapped_column(String(64))
    # Hypothetical probes are persisted for execution research but must never
    # be restored into, or reported as, the strategy's paper portfolio.
    is_shadow: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=false()
    )
    mode: Mapped[ExecutionMode] = mapped_column(EXECUTION_MODE, nullable=False)
    strategy: Mapped[str] = mapped_column(String(STRATEGY_NAME_LENGTH), nullable=False)
    side: Mapped[Side] = mapped_column(SIDE, nullable=False)
    status: Mapped[PositionStatus] = mapped_column(
        POSITION_STATUS, nullable=False, default=PositionStatus.OPEN
    )

    quantity: Mapped[Decimal] = mapped_column(QUANTITY, nullable=False)
    entry_price: Mapped[Decimal] = mapped_column(PRICE, nullable=False)
    exit_price: Mapped[Decimal | None] = mapped_column(PRICE)
    entry_notional_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False)

    realized_pnl_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    unrealized_pnl_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    fees_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)
    slippage_usd: Mapped[Decimal] = mapped_column(MONEY, nullable=False, default=0)

    opened_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    market: Mapped[Market] = relationship(lazy="raise")
    fills: Mapped[list[Fill]] = relationship(back_populates="position", lazy="raise")

    __table_args__ = (
        Index("ix_positions_status_opened", "status", "opened_at"),
        Index("ix_positions_market_opened", "market_id", "opened_at"),
        Index("ix_positions_mode_strategy", "mode", "strategy"),
        UniqueConstraint("mode", "attempt_id", "market_id", name="mode_attempt_market"),
        CheckConstraint("quantity > 0", name="quantity_positive"),
        CheckConstraint("entry_price > 0", name="entry_price_positive"),
        CheckConstraint("exit_price IS NULL OR exit_price > 0", name="exit_price_positive"),
        # A closed position must record when and at what price.
        CheckConstraint(
            "status <> 'CLOSED' OR (closed_at IS NOT NULL AND exit_price IS NOT NULL)",
            name="closed_position_complete",
        ),
    )
