"""create core data model

Revision ID: 61383e93b54b
Revises:
Create Date: 2026-09-11 03:33:38.982769+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "61383e93b54b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "markets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column(
            "market_type",
            sa.Enum("SPOT", "PERPETUAL", "FUTURE", name="market_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("base_asset", sa.String(length=16), nullable=False),
        sa.Column("quote_asset", sa.String(length=16), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("step_size", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("min_notional", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("maker_fee_bps", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("taker_fee_bps", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("contract_size", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("settlement_asset", sa.String(length=16), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "step_size IS NULL OR step_size > 0", name=op.f("ck_markets_step_size_positive")
        ),
        sa.CheckConstraint(
            "tick_size IS NULL OR tick_size > 0", name=op.f("ck_markets_tick_size_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_markets")),
        sa.UniqueConstraint("venue", "symbol", "market_type", name="venue_symbol_type"),
    )
    op.create_index("ix_markets_active", "markets", ["is_active", "market_type"], unique=False)
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("THEORETICAL", "PAPER", "LIVE", name="execution_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("cash_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_exposure_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("net_exposure_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("position_value_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("equity_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("open_positions", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gross_exposure_usd >= 0",
            name=op.f("ck_portfolio_snapshots_gross_exposure_non_negative"),
        ),
        sa.CheckConstraint(
            "open_positions >= 0", name=op.f("ck_portfolio_snapshots_open_positions_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
        sa.UniqueConstraint("mode", "captured_at", name="mode_captured_at"),
    )
    op.create_index(
        "ix_portfolio_snapshots_mode_captured",
        "portfolio_snapshots",
        ["mode", "captured_at"],
        unique=False,
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "STARTUP",
                "SHUTDOWN",
                "WS_CONNECTED",
                "WS_DISCONNECTED",
                "WS_RECONNECTED",
                "STALE_DATA",
                "DATA_GAP",
                "API_ERROR",
                "DATABASE_ERROR",
                "RECONCILIATION",
                name="system_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("INFO", "WARNING", "ERROR", "CRITICAL", name="severity", native_enum=False),
            nullable=False,
        ),
        sa.Column("component", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_events")),
    )
    op.create_index(
        "ix_system_events_component_occurred",
        "system_events",
        ["component", "occurred_at"],
        unique=False,
    )
    op.create_index("ix_system_events_occurred_at", "system_events", ["occurred_at"], unique=False)
    op.create_index(
        "ix_system_events_severity_occurred",
        "system_events",
        ["severity", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_system_events_type_occurred",
        "system_events",
        ["event_type", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "market_data",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("bid", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("ask", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("bid_size", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("ask_size", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("mid_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("spread", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("spread_bps", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("volume_24h", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("exchange_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ask >= bid", name=op.f("ck_market_data_book_not_crossed")),
        sa.CheckConstraint("bid > 0 AND ask > 0", name=op.f("ck_market_data_prices_positive")),
        sa.CheckConstraint(
            "bid_size >= 0 AND ask_size >= 0", name=op.f("ck_market_data_sizes_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_market_data_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_data")),
    )
    op.create_index("ix_market_data_local_ts", "market_data", ["local_timestamp"], unique=False)
    op.create_index(
        "ix_market_data_market_exch_ts",
        "market_data",
        ["market_id", "exchange_timestamp"],
        unique=False,
    )
    op.create_table(
        "order_books",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("bids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("asks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("depth_levels", sa.Integer(), nullable=False),
        sa.Column("exchange_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("depth_levels > 0", name=op.f("ck_order_books_depth_positive")),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_order_books_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_books")),
    )
    op.create_index("ix_order_books_local_ts", "order_books", ["local_timestamp"], unique=False)
    op.create_index(
        "ix_order_books_market_exch_ts",
        "order_books",
        ["market_id", "exchange_timestamp"],
        unique=False,
    )
    op.create_table(
        "trades_market",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("exchange_trade_id", sa.String(length=64), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column(
            "aggressor_side", sa.Enum("BUY", "SELL", name="side", native_enum=False), nullable=True
        ),
        sa.Column("exchange_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("local_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_trades_market_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_trades_market_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_trades_market_market_id_markets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades_market")),
        sa.UniqueConstraint("market_id", "exchange_trade_id", name="market_trade_id"),
    )
    op.create_index("ix_trades_market_local_ts", "trades_market", ["local_timestamp"], unique=False)
    op.create_index(
        "ix_trades_market_market_exch_ts",
        "trades_market",
        ["market_id", "exchange_timestamp"],
        unique=False,
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("THEORETICAL", "PAPER", "LIVE", name="execution_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("secondary_market_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "direction", sa.Enum("BUY", "SELL", name="side", native_enum=False), nullable=False
        ),
        sa.Column("market_data_id", sa.BigInteger(), nullable=True),
        sa.Column("secondary_market_data_id", sa.BigInteger(), nullable=True),
        sa.Column("entry_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("notional_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("gross_edge_bps", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("gross_edge_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("estimated_fees_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("estimated_slippage_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("funding_cost_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("borrow_cost_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("other_costs_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("safety_buffer_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("net_edge_bps", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column("net_edge_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("liquidity_usd", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DETECTED",
                "VALIDATED",
                "REJECTED",
                "PAPER_TRADE",
                "EXPIRED",
                "EXECUTED",
                "FAILED",
                name="opportunity_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entry_price > 0 AND exit_price > 0", name=op.f("ck_opportunities_prices_positive")
        ),
        sa.CheckConstraint(
            "estimated_fees_usd >= 0 AND estimated_slippage_usd >= 0 AND safety_buffer_usd >= 0",
            name=op.f("ck_opportunities_costs_non_negative"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_opportunities_quantity_positive")),
        sa.CheckConstraint(
            "secondary_market_id IS NULL OR secondary_market_id <> market_id",
            name=op.f("ck_opportunities_legs_differ"),
        ),
        sa.ForeignKeyConstraint(
            ["market_data_id"],
            ["market_data.id"],
            name=op.f("fk_opportunities_market_data_id_market_data"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_opportunities_market_id_markets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["secondary_market_data_id"],
            ["market_data.id"],
            name=op.f("fk_opportunities_secondary_market_data_id_market_data"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["secondary_market_id"],
            ["markets.id"],
            name=op.f("fk_opportunities_secondary_market_id_markets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
    )
    op.create_index("ix_opportunities_detected_at", "opportunities", ["detected_at"], unique=False)
    op.create_index(
        "ix_opportunities_market_detected",
        "opportunities",
        ["market_id", "detected_at"],
        unique=False,
    )
    op.create_index("ix_opportunities_net_edge", "opportunities", ["net_edge_bps"], unique=False)
    op.create_index(
        "ix_opportunities_status_detected", "opportunities", ["status", "detected_at"], unique=False
    )
    op.create_index(
        "ix_opportunities_strategy_detected",
        "opportunities",
        ["strategy", "detected_at"],
        unique=False,
    )
    op.create_index("ix_opportunities_uid", "opportunities", ["uid"], unique=True)
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum("THEORETICAL", "PAPER", "LIVE", name="execution_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="side", native_enum=False), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", "LIQUIDATED", name="position_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("entry_notional_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("realized_pnl_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("unrealized_pnl_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fees_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("slippage_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CLOSED' OR (closed_at IS NOT NULL AND exit_price IS NOT NULL)",
            name=op.f("ck_positions_closed_position_complete"),
        ),
        sa.CheckConstraint("entry_price > 0", name=op.f("ck_positions_entry_price_positive")),
        sa.CheckConstraint(
            "exit_price IS NULL OR exit_price > 0", name=op.f("ck_positions_exit_price_positive")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_positions_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_positions_market_id_markets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_positions_opportunity_id_opportunities"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(
        "ix_positions_market_opened", "positions", ["market_id", "opened_at"], unique=False
    )
    op.create_index("ix_positions_mode_strategy", "positions", ["mode", "strategy"], unique=False)
    op.create_index(
        "ix_positions_status_opened", "positions", ["status", "opened_at"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="side", native_enum=False), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("target_entry_price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("target_exit_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("expected_net_edge_bps", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "GENERATED",
                "APPROVED",
                "REJECTED",
                "EXECUTED",
                "EXPIRED",
                name="signal_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_signals_quantity_positive")),
        sa.CheckConstraint("target_entry_price > 0", name=op.f("ck_signals_entry_price_positive")),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_signals_market_id_markets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_signals_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index("ix_signals_generated_at", "signals", ["generated_at"], unique=False)
    op.create_index("ix_signals_opportunity", "signals", ["opportunity_id"], unique=False)
    op.create_index(
        "ix_signals_status_generated", "signals", ["status", "generated_at"], unique=False
    )
    op.create_table(
        "pnl_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("THEORETICAL", "PAPER", "LIVE", name="execution_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("strategy", sa.String(length=64), nullable=True),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column("window", sa.String(length=16), nullable=False),
        sa.Column("realized_pnl_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("unrealized_pnl_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fees_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("slippage_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("equity_usd", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("winning_trades", sa.Integer(), nullable=False),
        sa.Column("losing_trades", sa.Integer(), nullable=False),
        sa.Column("average_trade_usd", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("average_win_usd", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("average_loss_usd", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("max_drawdown_usd", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("win_rate", sa.Float(), nullable=True),
        sa.Column("profit_factor", sa.Float(), nullable=True),
        sa.Column("expectancy_usd", sa.Float(), nullable=True),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("sortino_ratio", sa.Float(), nullable=True),
        sa.Column("total_return_pct", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trade_count >= 0", name=op.f("ck_pnl_snapshots_trade_count_non_negative")
        ),
        sa.CheckConstraint(
            "win_rate IS NULL OR (win_rate >= 0 AND win_rate <= 1)",
            name=op.f("ck_pnl_snapshots_win_rate_ratio"),
        ),
        sa.CheckConstraint(
            "winning_trades + losing_trades <= trade_count",
            name=op.f("ck_pnl_snapshots_trade_splits_within_count"),
        ),
        sa.CheckConstraint(
            "winning_trades >= 0 AND losing_trades >= 0",
            name=op.f("ck_pnl_snapshots_trade_splits_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_pnl_snapshots_position_id_positions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pnl_snapshots")),
    )
    op.create_index(
        "ix_pnl_snapshots_mode_captured", "pnl_snapshots", ["mode", "captured_at"], unique=False
    )
    op.create_index(
        "ix_pnl_snapshots_strategy_captured",
        "pnl_snapshots",
        ["strategy", "captured_at"],
        unique=False,
    )
    op.create_table(
        "risk_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "PRE_TRADE_CHECK",
                "STALE_DATA",
                "LATENCY_EXCEEDED",
                "SLIPPAGE_EXCEEDED",
                "ORDER_SIZE_EXCEEDED",
                "POSITION_LIMIT_EXCEEDED",
                "EXPOSURE_LIMIT_EXCEEDED",
                "DAILY_LOSS_LIMIT",
                "CONSECUTIVE_LOSSES",
                "ABNORMAL_EXECUTION",
                "KILL_SWITCH",
                name="risk_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.Enum("APPROVED", "REJECTED", "PAUSED", name="risk_decision", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum("THEORETICAL", "PAPER", "LIVE", name="execution_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("signal_id", sa.BigInteger(), nullable=True),
        sa.Column("strategy", sa.String(length=64), nullable=True),
        sa.Column("limit_name", sa.String(length=64), nullable=True),
        sa.Column("limit_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("observed_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_risk_events_signal_id_signals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_events")),
    )
    op.create_index(
        "ix_risk_events_decision_occurred", "risk_events", ["decision", "occurred_at"], unique=False
    )
    op.create_index("ix_risk_events_occurred_at", "risk_events", ["occurred_at"], unique=False)
    op.create_index("ix_risk_events_signal", "risk_events", ["signal_id"], unique=False)
    op.create_index(
        "ix_risk_events_type_occurred", "risk_events", ["event_type", "occurred_at"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=True),
        sa.Column("risk_event_id", sa.BigInteger(), nullable=True),
        sa.Column("market_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("THEORETICAL", "PAPER", "LIVE", name="execution_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_order_id", sa.String(length=64), nullable=True),
        sa.Column("side", sa.Enum("BUY", "SELL", name="side", native_enum=False), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", name="order_type", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "time_in_force",
            sa.Enum("GTC", "IOC", "FOK", name="time_in_force", native_enum=False),
            nullable=True,
        ),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column("filled_quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("average_fill_price", sa.Numeric(precision=28, scale=12), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUBMITTED",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELLED",
                "REJECTED",
                "EXPIRED",
                "FAILED",
                name="order_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "filled_quantity <= quantity", name=op.f("ck_orders_filled_within_quantity")
        ),
        sa.CheckConstraint("filled_quantity >= 0", name=op.f("ck_orders_filled_non_negative")),
        sa.CheckConstraint("price IS NULL OR price > 0", name=op.f("ck_orders_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_orders_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["markets.id"],
            name=op.f("fk_orders_market_id_markets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["risk_event_id"],
            ["risk_events.id"],
            name=op.f("fk_orders_risk_event_id_risk_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_orders_signal_id_signals"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("mode", "client_order_id", name="mode_client_order_id"),
    )
    op.create_index("ix_orders_exchange_order_id", "orders", ["exchange_order_id"], unique=False)
    op.create_index("ix_orders_market_created", "orders", ["market_id", "created_at"], unique=False)
    op.create_index("ix_orders_mode_created", "orders", ["mode", "created_at"], unique=False)
    op.create_index("ix_orders_status_created", "orders", ["status", "created_at"], unique=False)
    op.create_table(
        "fills",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("position_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum("THEORETICAL", "PAPER", "LIVE", name="execution_mode", native_enum=False),
            nullable=False,
        ),
        sa.Column("exchange_fill_id", sa.String(length=64), nullable=True),
        sa.Column("price", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("fee_usd", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("fee_asset", sa.String(length=16), nullable=True),
        sa.Column("slippage_bps", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("is_maker", sa.Boolean(), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("price > 0", name=op.f("ck_fills_price_positive")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_fills_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_fills_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_fills_position_id_positions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("order_id", "exchange_fill_id", name="order_exchange_fill_id"),
    )
    op.create_index("ix_fills_filled_at", "fills", ["filled_at"], unique=False)
    op.create_index("ix_fills_order", "fills", ["order_id"], unique=False)
    op.create_index("ix_fills_position", "fills", ["position_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fills_position", table_name="fills")
    op.drop_index("ix_fills_order", table_name="fills")
    op.drop_index("ix_fills_filled_at", table_name="fills")
    op.drop_table("fills")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index("ix_orders_mode_created", table_name="orders")
    op.drop_index("ix_orders_market_created", table_name="orders")
    op.drop_index("ix_orders_exchange_order_id", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_risk_events_type_occurred", table_name="risk_events")
    op.drop_index("ix_risk_events_signal", table_name="risk_events")
    op.drop_index("ix_risk_events_occurred_at", table_name="risk_events")
    op.drop_index("ix_risk_events_decision_occurred", table_name="risk_events")
    op.drop_table("risk_events")
    op.drop_index("ix_pnl_snapshots_strategy_captured", table_name="pnl_snapshots")
    op.drop_index("ix_pnl_snapshots_mode_captured", table_name="pnl_snapshots")
    op.drop_table("pnl_snapshots")
    op.drop_index("ix_signals_status_generated", table_name="signals")
    op.drop_index("ix_signals_opportunity", table_name="signals")
    op.drop_index("ix_signals_generated_at", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_positions_status_opened", table_name="positions")
    op.drop_index("ix_positions_mode_strategy", table_name="positions")
    op.drop_index("ix_positions_market_opened", table_name="positions")
    op.drop_table("positions")
    op.drop_index("ix_opportunities_uid", table_name="opportunities")
    op.drop_index("ix_opportunities_strategy_detected", table_name="opportunities")
    op.drop_index("ix_opportunities_status_detected", table_name="opportunities")
    op.drop_index("ix_opportunities_net_edge", table_name="opportunities")
    op.drop_index("ix_opportunities_market_detected", table_name="opportunities")
    op.drop_index("ix_opportunities_detected_at", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_trades_market_market_exch_ts", table_name="trades_market")
    op.drop_index("ix_trades_market_local_ts", table_name="trades_market")
    op.drop_table("trades_market")
    op.drop_index("ix_order_books_market_exch_ts", table_name="order_books")
    op.drop_index("ix_order_books_local_ts", table_name="order_books")
    op.drop_table("order_books")
    op.drop_index("ix_market_data_market_exch_ts", table_name="market_data")
    op.drop_index("ix_market_data_local_ts", table_name="market_data")
    op.drop_table("market_data")
    op.drop_index("ix_system_events_type_occurred", table_name="system_events")
    op.drop_index("ix_system_events_severity_occurred", table_name="system_events")
    op.drop_index("ix_system_events_occurred_at", table_name="system_events")
    op.drop_index("ix_system_events_component_occurred", table_name="system_events")
    op.drop_table("system_events")
    op.drop_index("ix_portfolio_snapshots_mode_captured", table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index("ix_markets_active", table_name="markets")
    op.drop_table("markets")
    # ### end Alembic commands ###
