"""allow missing exchange timestamps

Revision ID: 9ef15a885330
Revises: 61383e93b54b
Create Date: 2026-09-11 04:08:45.128057+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9ef15a885330"
down_revision: str | None = "61383e93b54b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "market_data",
        "exchange_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "order_books",
        "exchange_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    # Added by hand: Alembic does not autogenerate CHECK constraints.
    # Latency is an exchange->local delta, so it cannot exist without the
    # exchange clock it is derived from.
    op.create_check_constraint(
        "latency_requires_exchange_clock",
        "market_data",
        "latency_ms IS NULL OR exchange_timestamp IS NOT NULL",
    )


def downgrade() -> None:
    # Bare name: the metadata naming convention expands it to
    # ck_market_data_latency_requires_exchange_clock.
    op.drop_constraint("latency_requires_exchange_clock", "market_data", type_="check")
    # Rows with a NULL exchange_timestamp must be removed before the column can
    # be made NOT NULL again.
    op.execute("DELETE FROM market_data WHERE exchange_timestamp IS NULL")
    op.execute("DELETE FROM order_books WHERE exchange_timestamp IS NULL")
    op.alter_column(
        "order_books",
        "exchange_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "market_data",
        "exchange_timestamp",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###
